hunzzzzz/catch-table

src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/response/StoreResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/repository/StoreRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
#2 
누락된 어노테이션은 없는지 한 번씩 확인해주세요!
=> [Feat] Store 엔티티 관련 기본 세팅

src/main/kotlin/org/team/b6/catchtable/CatchTableApplication.kt
=> BugFix: DB에 데이터 등록 시 발생하는 PropertyValueException 해결

src/main/kotlin/org/team/b6/catchtable/CatchTableApplication.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/SignupMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/UpdateMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/response/MemberResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/repository/MemberRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt
#4
Request Dto에서 to() 메소드가 어떤 역할인지 잘 이해는 못했는데, 일단 추가하였습니다. 상의가 필요할 것 같습니다.
creatAt을 Response에서 표기해줘야 하는지 한번 얘기해보고 싶습니다.
LocalDateTime과 ZonedDateTime에 관해 검색해봤는데, 두개의 차이에 관해 얘기해 보면 좋을 것 같습니다.
=> [Feat] Member 엔티티 관련 기본 세팅

src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/global/dto/ErrorResponse.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/InvalidStoreCategoryException.kt
#10 
ErrorResponse 양식 괜찮은지 확인 한번만 해주세요~
=> Feat: 에러를 전역적으로 처리하는 기능 구현

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/StoreRequirement.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreRequirementService.kt
=> Refactor: StoreRequirement의 requireTo를 requireOf로 수정

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/SignupMemberRequest.kt
=> [Feat] 회원가입 시 비밀번호, 닉네임 생성 및 규격검사

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt
=> [Feat] 식당의 등록/삭제 요청 시 ADMIN이 해당 요청을 승인한 경우 메일 발송

src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/Store.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
=> [Feat] Store 엔티티에 belongsTo 속성 추가

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/UpdateMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/model/Member.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt
> #59
password 확인을 위해 dto에 confirmPassword 선언
service에 nickname과 password 중복 검사 및 유효성 검사
updateMember 메서드 추가
업데이트를 하기 위해 수정 가능하게 하기 위해 수정
> 훈님 부탁해여
=> [Feat] 프로필수정

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt
> #62
- AdminService에 삭제 승인시 리뷰전체 삭제 기능 추가
=> 식당 삭제시 해당 리뷰 전체 삭제 기능 추가

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt
=> [Refactor] AdminController, AdminService 코드 리팩토링

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/SignupMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt
=> [BugFix] 회원가입 시 Validation 미작동 오류 해결

src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/response/StoreResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/Store.kt
=> [Refactor] Store의 openTime과 closeTime의 자료형을 Int로 변경

src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/EtiquetteException.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/org/team/b6/catchtable/global/variable/Variables.kt
=> feat:리뷰 등록시 비속어 필터 기능 추가

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/controller/ReviewController.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/InvalidRoleException.kt, src/main/kotlin/org/team/b6/catchtable/global/service/GlobalService.kt
=> [Refactor] ADMIN 관련 클래스 코드 리팩토링 및 권한 부여

src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/controller/TimeTableController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/TimeTableRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/response/StoreResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/Store.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/TimeTable.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/repository/TimeTableRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/TimeTableService.kt
#85 
- Store에서 TimeTable의 객체를 갖고 있기로 결정
- Store의 오픈시간/마감시간 범위에 벗어난 시간에 값을 지정한 경우 Exception 발생
아직 확정된 사안이 아니라 TimeTable 관련 클래스/메서드는 모두 주석처리 하였습니다.
=> [Feat] TimeTable 엔티티 생성

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/repository/ReviewRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/response/StoreResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/global/service/GlobalService.kt
#103 
- StoreService 뿐만 아니라 다른 클래스에서도 사용해야 하기 때문
- 이와 연관된 클래스/메서드 수정
=> [Feat] Store의 평균 별점을 계산하는 로직 구현

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/response/StoreResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/StoreRequirementDeniedException.kt, src/main/kotlin/org/team/b6/catchtable/global/service/GlobalService.kt
#105 
- 원 위치는 GlobalService 였으나, GlobalService는 엔티티의 전체조회/단일조회의 목적으로만 사용하도록 결정
=> [Feat] Store 관련 클래스 리팩토링 및 권한 부여

src/main/kotlin/org/team/b6/catchtable/domain/reservation/controller/ReservationController.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/dto/ReservationRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/dto/ReservationResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/model/Reservation.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/repository/ReservationRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/service/ReservationService.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/service/ReservationServiceImpl.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/repository/StoreRepository.kt
> #115 
> 인텔리제이 내의 run에는 문제가 없으나 각 기능들이 원하는대로 작동하는지는 추후 확인해야 함
=> reservation 기능 추가

build.gradle.kts, src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/resources/static/css/index.css, src/main/resources/static/css/signup.css, src/main/resources/static/index.html, src/main/resources/static/js/signup.js, src/main/resources/static/signup.html
=> [FrontEnd] 회원가입 페이지 구현

src/main/kotlin/org/team/b6/catchtable/domain/blacklist/entity/BlackList.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt
=> [Refactor] AdminService, AdminController 코드 리팩토링

src/main/kotlin/org/team/b6/catchtable/domain/reservation/controller/ReservationController.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/model/Reservation.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/service/ReservationService.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/service/ReservationServiceImpl.kt
> #122 
> 컨플릭트 위험이 있으니 1차 수정 필요
=> bytime 문제 해결

src/main/kotlin/org/team/b6/catchtable/domain/blacklist/entity/BlackList.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/global/util/EntityFinderService.kt, src/main/kotlin/org/team/b6/catchtable/global/util/MailSenderService.kt
=> [BugFix] util 패키지 하위 클래스 버그 수정

src/main/kotlin/org/team/b6/catchtable/domain/reservation/model/Reservation.kt
=> reservationlist fixed
