hunzzzzz/catch-table

src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/response/StoreResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/StoreCategory.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/repository/StoreRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
#5 
- StoreController와 StoreService에 findAllStoresByCategory 메서드 생성
- StoreService 내에 category를 검증하는 getCategory 내부 메서드 생성
- StoreController와 StoreService에 findAllStoresByCategoryWithSortCriteria 메서드 생성
- StoreService 내에 criteria를 검증하는 getCriteria 내부 메서드 생성
- 하나는 카테고리 별 조회, 나머지는 카테고리 + 정렬 조건으로 조회
- 추후 to메서드를 통해 엔티티로 변환할 때 StoreCategory enum class 자료형으로 변환
예외 처리는 추후에 진행할 예정입니다.
=> Feat : 전체 식당 목록 카테고리 별 조회 기능 구현

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/response/MemberResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt, src/main/kotlin/org/team/b6/catchtable/global/security/PasswordEncoderConfig.kt
> #12 
MemberController와 MemberService에 getMemberList를 생성
개별은 getMember로 생성
=> [Feat] 멤버 전체 목록 조회 및 개별 조회, password 인코딩

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/response/AdminResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/StoreRequirement.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/StoreRequirementCategory.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/repository/StoreRequirementRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreRequirementService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
#14
Store에 대한 등록/변경/삭제를 하기전 ADMIN의 승인이 필요하기 때문에, 요청이 바로 StoreRepository에 저장되면 안된다. 따라서, 중간 엔티티인 StoreRequirement를 만들어서, OWNER는 StoreRequirement로 요청을 보내고, ADMIN은 StoreRequirement 요청을 확인하고 승인/거절하는 로직으로 변경하였다.
(기존에는 StoreService로 바로 request를 넘겨주는 방식)
엔티티를 아예 새로 하나 만든거라 유심히 봐주세요!
=> Feat: Store의 등록/변경/삭제를 위한 중간 엔티티 생성

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/SignupMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/response/MemberResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/repository/MemberRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt
#20 
when문을 사용하여 USER,OWNER 이외의 입력은 throw Exception하게 구현했습니다.(Exception은 추후 작성예정)
트러블슈팅하며 수정하긴 했는데, 크게 상관은 없어 변경 가능성 높음
로그인 메소드 구현시에 사용할 예정입니다.
> 회원가입시 passwordEncoder를 사용했는데, security가 import 돼있지 않으시다면 에러가 발생할 가능성이 있습니다.
security import는 주의해서 해주세요 테스트시에 필터가 걸립니다!
=> feat : 회원가입기능 추가

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/StoreRequirement.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreRequirementService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
#19 
- UPDATE, DELETE 시 수정/삭제의 대상이 되는 Store의 Id도 같이 저장
- FK가 아님을 구분하기 위해 컬럼명을 store_id가 아닌 requireTo로 설정
- CREATE 시에는 추가하고자 하는 store 객체를 StoreService에 넘겨줌
- UPDATE 시에는 변경하고자 하는 대상 store의 Id와, StoreRequest를 새로 생성하여 StoreService에 넘겨줌
- DELETE 시에는 삭제하고자 하는 대상 store의 Id를 StoreService에 넘겨줌
=> [Feat] StoreRequirement를 활용한 Store의 등록/수정/삭제 기능 재수정

build.gradle.kts, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/global/variable/Strings.kt
#32 
- JavaMailSender과 SimpleMailMessage 객체를 활용하여 메일 전송
- 등록/수정/삭제 총 3가지 경우로 나누어 코드 작성
현재 dev 브랜치에서 테스트를 완벽하게 수행할 수 없는 상황이라 추후에 코드가 변경될 수 있습니다.
=> [Feat] Store의 등록/수정/삭제 요청 후, 이메일을 통한 승인 여부 전송

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreRequirementService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/global/variable/Variables.kt
#37
- 추후 프로젝트 확장성을 위해 요청 기록도 일정 기간 보관
- ADMIN이 요청을 승인한 경우, 단순히 isAccepted 속성을 true로 변경
=> [Refactor] Store 관련 클래스 코드 리팩토링

src/main/kotlin/org/team/b6/catchtable/global/dto/ErrorMessageResponse.kt, src/main/kotlin/org/team/b6/catchtable/global/security/CustomAccessDeniedHandler.kt, src/main/kotlin/org/team/b6/catchtable/global/security/CustomAuthenticationEntrypoint.kt, src/main/kotlin/org/team/b6/catchtable/global/security/SecurityConfig.kt
#45 
SecurityConfig는 환경에 따라 다르게 작동할 수 있으니 정말정말 유의하셔야합니다!!!!
=> [feat] 인증,인가 처리시 401,403 Exception처리 필터추가

src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/SignupMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt
=> [BugFix] InvalidCredentialException 추가, 닉네임,비밀번호 유효성검사 수정

src/main/kotlin/org/team/b6/catchtable/domain/store/repository/StoreRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
=> [BugFix] Store 정보 수정 시 중복 로직이 오적용되는 버그 수정

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/global/service/GlobalService.kt, src/main/kotlin/org/team/b6/catchtable/global/variable/Variables.kt
#64 
- 필요한 클래스에서 GlobalService 객체를 주입받아 단일 조회/전체 조회를 사용
=> [Feat] ADMIN 관련 클래스들 리팩토링

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/SignupMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/global/variable/Variables.kt
#71 
임시로 만든 기능이라 월요일 오전에 삭제 예정입니다!
=> [Test] Swagger 테스트를 위한 임시 ADMIN 회원가입 기능 구현

src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/model/Store.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt
=> [Feat] 주문 많은 수로 Store를 정렬하는 로직 구현

build.gradle.kts, src/main/kotlin/org/team/b6/catchtable/domain/store/controller/StoreController.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/dto/request/StoreRequest.kt, src/main/kotlin/org/team/b6/catchtable/global/aop/ValidCategory.kt, src/main/kotlin/org/team/b6/catchtable/global/aop/Validator.kt, src/main/kotlin/org/team/b6/catchtable/global/dto/ErrorResponse.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt
=> [Feat] Store 등록 과정에서 Validation 구현

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/model/Member.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt
#81
새로 Entity에 추가한 isDeleted 필드를 true로 지정해주며 탈퇴한 회원임을 명시하고, 닉네임을 탈퇴한회원{memberId} 형식으로 변환하며 role을 WITHDRAWN으로 변경해줍니다. 이는 db내의 데이터를 실제로 삭제하는 것이 아닌, 데이터는 유지하되 isDeleted 필드를 이용한 soft-delete 방식입니다.  
저희 정책상 OWNER가 탈퇴할때 store와 review를 같이 hard-delete 방식의 삭제하는 로직도 임시로 주석으로 추가해놨습니다. 다만 이것도 구현한다면, store,review에도 isDeleted 필드를 이용해 soft=delete로 선회하는게 더 긍정적이지 않을까 생각합니다.
=> [Feat] : withdraw 회원탈퇴 메소드 추가

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/MemberController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/request/UpdateMemberRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/MemberService.kt
=> [refator] : @AuthenticationPrincipal 어노테이션으로 유저인증 변경

src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/controller/ReviewController.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/model/Review.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/model/ReviewStatus.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt
#101 
- 요청의 주체가 리뷰가 달린 식당의 주인인지 검증 후, status를 REQUIRED_FOR_DELETE로 변경
- ADMIN이 처리해야 하는 리뷰 삭제 요구사항들을 조회하는 메서드
=> [Feat] OWNER의 리뷰 삭제 요청을 ADMIN이 승인/거절하는 로직 구현 Part2

src/main/kotlin/org/team/b6/catchtable/domain/blacklist/entity/BlackList.kt, src/main/kotlin/org/team/b6/catchtable/domain/blacklist/entity/BlackListReason.kt, src/main/kotlin/org/team/b6/catchtable/domain/blacklist/repository/BlackListRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/model/Member.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/InvalidRoleException.kt, src/main/kotlin/org/team/b6/catchtable/global/service/UtilService.kt, src/main/kotlin/org/team/b6/catchtable/global/variable/Variables.kt
#107 
- BlackListReason(경고 사유) enum 클래스 생성 (TROLLING_REVIEW, NO_SHOW)
- 해당 멤버에게 이메일을 전송하여 정지 사실을 알림
- Variables에 계정 정지 시 메일 제목/내용 추가
이슈 규모가 너무 커져서 두 개의 파트로 나눠서 올릴 예정입니다!
=> [Feat] BlackList 엔티티 생성 Part1

src/main/kotlin/org/team/b6/catchtable/domain/review/dto/request/ReviewRequest.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt
=> [Refactor] ReviewRequest에서 memberId를 받지 않도록 설정

src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/repository/ReviewRepository.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/global/service/GlobalService.kt
#111 
- ReviewRepository의 getAllByStoreId 메서드 제거 (JPA 명명 규칙 오류)
- filter를 통해 storeId를 비교하는 것으로 변경
=> [Refactor] Store 조회 시 하위 Review가 조회되지 않던 버그 수정

src/main/kotlin/org/team/b6/catchtable/CatchTableApplication.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/controller/AdminController.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/dto/response/BannedMemberResponse.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/model/Member.kt, src/main/kotlin/org/team/b6/catchtable/domain/member/service/AdminService.kt, src/main/kotlin/org/team/b6/catchtable/domain/reservation/service/ReservationServiceImpl.kt, src/main/kotlin/org/team/b6/catchtable/domain/review/service/ReviewService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/StoreService.kt, src/main/kotlin/org/team/b6/catchtable/domain/store/service/TimeTableService.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/BannedUserException.kt, src/main/kotlin/org/team/b6/catchtable/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/org/team/b6/catchtable/global/service/FindingEntityService.kt
#113 
- AdminController, AdminService에 findAllBannedMembers 메서드 추가
- BannedMemberResponse 클래스를 생성하여 리턴값 조정
- AdminService에서 Scheduled 어노테이션을 활용
- Member 엔티티에 liftSuspension 메서드를 생성하여 계정 정지 기간이 종료되면 USER의 banned_expiriation이 null로 변경
=> [Feat] BlackList 엔티티 생성 Part2
